theme: jekyll-theme-hacker
title: Semper ex Datis "Always about the Data"
description: 'U.S. Marine | Data Scientist where it counts! CxO interpreter, techie-whisperer, and non-corporate clone. "Experience is directly & exponentially proportional to the amount of code refactored" — Everyone who has coded'
